# Generated by Django 4.2.16 on 2026-05-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=5)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_payout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('mpesa', 'M-Pesa')], max_length=10)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('released', 'Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='vendor.vendorjob')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_earned', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_funded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'escrow_payments',
                'indexes': [models.Index(fields=['status'], name='escrow_paym_status_b4b2e1_idx')],
            },
        ),
    ]
