# Generated by Django 4.2.16 on 2026-05-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('headline', models.CharField(blank=True, max_length=300)),
                ('bio', models.TextField(blank=True)),
                ('profession', models.CharField(db_index=True, max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], db_index=True, default='offline', max_length=20)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'indexes': [models.Index(fields=['profession', 'availability'], name='profiles_profess_2c9664_idx'), models.Index(fields=['country'], name='profiles_country_865c34_idx')],
            },
        ),
    ]
