# Generated by Django 4.2.16 on 2026-05-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScoreHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_merit_score', models.FloatField()),
                ('psp_consistency_score', models.FloatField()),
                ('cohort_performance_score', models.FloatField()),
                ('vendor_rating_score', models.FloatField()),
                ('authenticity_confidence', models.FloatField()),
                ('reason', models.CharField(max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_score_history',
                'indexes': [models.Index(fields=['user', 'recorded_at'], name='trust_score_user_id_b6622a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('psp_consistency_score', models.FloatField(default=0.0)),
                ('cohort_performance_score', models.FloatField(default=0.0)),
                ('vendor_rating_score', models.FloatField(default=0.0)),
                ('authenticity_confidence', models.FloatField(default=0.0)),
                ('overall_merit_score', models.FloatField(db_index=True, default=0.0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('apex', 'APEX')], db_index=True, default='bronze', max_length=20)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_scores',
                'indexes': [models.Index(fields=['overall_merit_score'], name='trust_score_overall_580f9b_idx')],
            },
        ),
    ]
