# Generated by Django 4.2.16 on 2026-05-21 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profession', models.CharField(db_index=True, max_length=100)),
                ('global_rank', models.PositiveIntegerField(db_index=True, null=True)),
                ('profession_rank', models.PositiveIntegerField(db_index=True, null=True)),
                ('country_rank', models.PositiveIntegerField(null=True)),
                ('previous_global_rank', models.PositiveIntegerField(null=True)),
                ('rank_movement', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rankings',
                'indexes': [models.Index(fields=['profession', 'profession_rank'], name='rankings_profess_e94fd4_idx')],
            },
        ),
    ]
