# Generated by Django 4.2.16 on 2026-08-19 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cohorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSPRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('psp_tier', models.CharField(max_length=64)),
                ('amount_expected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Payment Review'), ('confirmed', 'Payment Confirmed'), ('active', 'PSP Active'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psp_registrations', to='cohorts.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psp_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psp_registrations',
                'unique_together': {('user', 'cohort', 'psp_tier')},
            },
        ),
        migrations.CreateModel(
            name='PSPVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='cohorts.pspregistration')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'psp_verifications',
            },
        ),
    ]
