# Generated by Django 5.2.17 on 2026-08-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0002_pspregistration_pspverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='assessment_unlock_threshold',
            field=models.PositiveIntegerField(choices=[(20, '20 participants'), (50, '50 participants'), (100, '100 participants')], default=20, help_text='Minimum verified participants required before assessments can start.'),
        ),
        migrations.AlterField(
            model_name='pspregistration',
            name='psp_tier',
            field=models.CharField(choices=[('10kes', 'KES 10'), ('100kes', 'KES 100'), ('1000kes', 'KES 1,000')], max_length=64),
        ),
    ]
