# Generated by Django 5.2.17 on 2026-08-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0003_cohort_assessment_unlock_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='video_url',
            field=models.URLField(blank=True, help_text='Video source for this assessment.'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='question_order',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='video_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='video_watched_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pspregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('review', 'Payment Review'), ('failed', 'Payment Failed'), ('confirmed', 'Payment Confirmed'), ('active', 'PSP Active'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
