# Generated by Django 5.2.17 on 2026-08-19 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0004_assessment_video_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='account_based_marketing_budget',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='cohort',
            name='consistency_coach_payout',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='cohort',
            name='improvement_coach_payout',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='cohort',
            name='skills_coach_payout',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.CreateModel(
            name='CohortWalletEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wallet', models.CharField(choices=[('mentor_payout', 'Mentor Payout'), ('account_based_marketing', 'Account-Based Marketing'), ('admin', 'Admin Wallet')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_entries', to='cohorts.cohort')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohort_wallet_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cohort_wallet_entries',
            },
        ),
        migrations.CreateModel(
            name='CohortCoachAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('skills', 'Skills Coach'), ('consistency', 'Consistency Coach'), ('improvement', 'Improvement Coach')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payout_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to='cohorts.cohort')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cohort_coach_assignments',
                'constraints': [models.UniqueConstraint(fields=('cohort', 'user', 'role'), name='unique_cohort_coach_role')],
            },
        ),
    ]
