# Generated by Django 5.2.17 on 2026-08-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohorts', '0005_cohort_account_based_marketing_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='payment_tier',
            field=models.CharField(choices=[('10kes', 'KES 10'), ('100kes', 'KES 100'), ('1000kes', 'KES 1,000')], db_index=True, default='100kes', max_length=10),
        ),
    ]
